import Navbar from '@/components/Navbar';
import './globals.css';
// import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });
import { Roboto } from 'next/font/google';
import Sidebar from '@/components/Sidebar';

const roboto = Roboto({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${roboto.className} bg-backgroundColor`}>
        <Navbar />
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
